name: Deploy CloudFormation

on:
  workflow_call:
    inputs:
      stack-name:
        description: 'CloudFormation stack name'
        required: true
        type: string
      template:
        description: 'Path to CloudFormation template'
        required: true
        type: string
      parameter-overrides:
        description: 'CloudFormation parameter overrides'
        required: false
        type: string
        default: ''
      project:
        description: 'Value for the Project tag applied to the stack'
        required: true
        type: string
    outputs:
      stack-outputs-json:
        description: 'All CloudFormation stack outputs as JSON'
        value: ${{ jobs.deploy.outputs.stack-outputs-json }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      stack-outputs-json: ${{ toJSON(steps.deploy.outputs) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Deploy to AWS CloudFormation
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@81e3b03d2266bcb76c4bcc37a7d71d9cb67838bb # v2.2.0
        with:
          name: ${{ inputs.stack-name }}
          template: ${{ inputs.template }}
          fail-on-empty-changeset: false
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: ${{ inputs.parameter-overrides }}
          tags: '[{"Key":"Project","Value":"${{ inputs.project }}"}]'
